name: Build React App & Run K6 Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar dependencias de Node y construir el proyecto
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build React app (Vite)
        run: npm run build

      # 3️⃣ Instalar k6
      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      # 4️⃣ Ejecutar las pruebas (usando tu script.js)
      - name: Run K6 tests
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          BASE_URL: https://pruebas-de-carga-k6.onrender.com
        run: |
          # Verificar que el endpoint sea alcanzable antes de ejecutar k6
          echo "Comprobando disponibilidad de $BASE_URL"
          curl -I --max-time 15 --retry 2 --retry-delay 2 "$BASE_URL" || {
            echo "ERROR: $BASE_URL no es alcanzable";
            exit 1;
          }

          # Ejecutar pruebas en k6 Cloud y pasar BASE_URL explícitamente
          k6 cloud -e BASE_URL="$BASE_URL" tests/test.js
